// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null

    this._missing = 2
  }

  add (name, handler) {
    switch (name) {
      case '@registry/add-writer':
        this._handler0 = handler
        break
      case '@registry/put-entry':
        this._handler1 = handler
        break
      default:
        throw new Error('Cannot register a handler for a nonexistent route: ' + name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@registry/add-writer"')
    assert(this._handler1 !== null, 'Missing handler for "@registry/put-entry"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      default:
        throw new Error('Handler not found for ID:' + op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@registry/add-writer',
  id: 0,
  enc: getEncoding('@registry/writer')
}

const route1 = {
  name: '@registry/put-entry',
  id: 1,
  enc: getEncoding('@registry/entry')
}

function getRouteByName (name) {
  switch (name) {
    case '@registry/add-writer':
      return route0
    case '@registry/put-entry':
      return route1
    default:
      throw new Error('Handler not found for name: ' + name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    default:
      throw new Error('Handler not found for ID: ' + id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router
}
